CREATE TYPE status AS ENUM ('active', 'disabled');

CREATE TABLE IF NOT EXISTS applicants (
  id SERIAL PRIMARY KEY NOT NULL,
  email CHAR(255) NOT NULL,
  name CHAR(255) NOT NULL,
  status status NOT NULL DEFAULT 'active',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS positions (
  id SERIAL PRIMARY KEY NOT NULL,
  name CHAR(255) NOT NULL,
  max_hired INT NOT NULL,
  status status NOT NULL DEFAULT 'active',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);